[package]
name = "raytracer"
version = "0.1.0"
authors = ["Arlo J Purcell <arlo@indeed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.13"
nalgebra = "0.24.1"
